export const ADD_TRANSACTION = 'transactions/ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'transactions/REMOVE_TRANSACTION';
export const CHANGE_TRANSACTION = 'transactions/CHANGE_TRANSACTION';
export const CHANGE_NEW_TRANSACTION_FIELD = 'transactions/CHANGE_NEW_TRANSACTION_FIELD';
